fix 1.8.8 NoSuchMethodError
issue was caused by UniversalSkinFactory.java change in f1104d1feec985b7630a1ae8b256a0a1e629f6f2

Now using the right error to avoid confusion.